=== prahaladvathsan/sofascore-politics/data/schemas/party.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://political-report-card.example/data/schemas/party.schema.json",
  "title": "Party",
  "type": "object",
  "additionalProperties": false,
  "required": ["id", "name", "short_name", "color", "official_url", "_meta"],
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "short_name": {
      "type": "string"
    },
    "color": {
      "type": "string",
      "pattern": "^#[0-9A-Fa-f]{6}$"
    },
    "official_url": {
      "type": "string",
      "format": "uri"
    },
    "_meta": {
      "$ref": "common.schema.json#/definitions/meta"
    }
  }
}

=== prahaladvathsan/sofascore-politics/data/parties/JSP.json
{
  "id": "JSP",
  "name": "Janasena Party",
  "short_name": "JSP",
  "color": "#c62828",
  "official_url": "https://janasenaparty.org/",
  "_meta": {
    "sources": [
      {
        "url": "https://en.wikipedia.org/wiki/Janasena_Party",
        "name": "Wikipedia - Janasena Party",
        "retrieved_at": "2026-04-23T00:00:00+05:30"
      }
    ]
  }
}
