=== prahaladvathsan/sofascore-politics/data/schemas/party.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://political-report-card.example/data/schemas/party.schema.json",
  "title": "Party",
  "type": "object",
  "additionalProperties": false,
  "required": ["id", "name", "short_name", "color", "official_url", "_meta"],
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "short_name": {
      "type": "string"
    },
    "color": {
      "type": "string",
      "pattern": "^#[0-9A-Fa-f]{6}$"
    },
    "official_url": {
      "type": "string",
      "format": "uri"
    },
    "_meta": {
      "$ref": "common.schema.json#/definitions/meta"
    }
  }
}

=== prahaladvathsan/sofascore-politics/data/parties/AAP.json
{
  "id": "AAP",
  "name": "Aam Aadmi Party",
  "short_name": "AAP",
  "color": "#0072bc",
  "official_url": "https://aamaadmiparty.org/",
  "_meta": {
    "sources": [
      {
        "url": "https://en.wikipedia.org/wiki/Aam_Aadmi_Party",
        "name": "Wikipedia - Aam Aadmi Party",
        "retrieved_at": "2026-04-23T00:00:00+05:30"
      }
    ]
  }
}

=== prahaladvathsan/sofascore-politics/data/parties/AIADMK.json
{
  "id": "AIADMK",
  "name": "All India Anna Dravida Munnetra Kazhagam",
  "short_name": "AIADMK",
  "color": "#2b8a3e",
  "official_url": "https://aiadmk.com/",
  "_meta": {
    "sources": [
      {
        "url": "https://en.wikipedia.org/wiki/All_India_Anna_Dravida_Munnetra_Kazhagam",
        "name": "Wikipedia - AIADMK",
        "retrieved_at": "2026-04-22T00:00:00+05:30"
      }
    ]
  }
}

=== prahaladvathsan/sofascore-politics/data/parties/IND.json
{
  "id": "IND",
  "name": "Independent",
  "short_name": "IND",
  "color": "#6b7280",
  "official_url": "https://en.wikipedia.org/wiki/Independent_politician",
  "_meta": {
    "sources": [
      {
        "url": "https://en.wikipedia.org/wiki/Independent_politician",
        "name": "Wikipedia - Independent politician",
        "retrieved_at": "2026-04-23T00:00:00+05:30"
      }
    ]
  }
}

=== prahaladvathsan/sofascore-politics/data/parties/CPI.json
{
  "id": "CPI",
  "name": "Communist Party of India",
  "short_name": "CPI",
  "color": "#c62828",
  "official_url": "https://communistparty.in/",
  "_meta": {
    "sources": [
      {
        "url": "https://en.wikipedia.org/wiki/Communist_Party_of_India",
        "name": "Wikipedia - Communist Party of India",
        "retrieved_at": "2026-04-23T00:00:00+05:30"
      }
    ]
  }
}

=== prahaladvathsan/sofascore-politics/data/parties/AIFB.json
{
  "id": "AIFB",
  "name": "All India Forward Bloc",
  "short_name": "AIFB",
  "color": "#c62828",
  "official_url": "https://allindiaforwardbloc.org/",
  "_meta": {
    "sources": [
      {
        "url": "https://en.wikipedia.org/wiki/All_India_Forward_Bloc",
        "name": "Wikipedia - All India Forward Bloc",
        "retrieved_at": "2026-04-23T00:00:00+05:30"
      }
    ]
  }
}

=== prahaladvathsan/sofascore-politics/data/parties/IUML.json
{
  "id": "IUML",
  "name": "Indian Union Muslim League",
  "short_name": "IUML",
  "color": "#2e7d32",
  "official_url": "https://iumlkerala.org/",
  "_meta": {
    "sources": [
      {
        "url": "https://en.wikipedia.org/wiki/Indian_Union_Muslim_League",
        "name": "Wikipedia - Indian Union Muslim League",
        "retrieved_at": "2026-04-23T00:00:00+05:30"
      }
    ]
  }
}

=== prahaladvathsan/sofascore-politics/data/parties/INC.json
{
  "id": "INC",
  "name": "Indian National Congress",
  "short_name": "INC",
  "color": "#1f57a4",
  "official_url": "https://www.inc.in/",
  "_meta": {
    "sources": [
      {
        "url": "https://en.wikipedia.org/wiki/Indian_National_Congress",
        "name": "Wikipedia - Indian National Congress",
        "retrieved_at": "2026-04-22T00:00:00+05:30"
      }
    ]
  }
}

=== prahaladvathsan/sofascore-politics/data/parties/YSRCP.json
{
  "id": "YSRCP",
  "name": "YSR Congress Party",
  "short_name": "YSRCP",
  "color": "#1e88e5",
  "official_url": "https://www.ysrcongress.com/",
  "_meta": {
    "sources": [
      {
        "url": "https://en.wikipedia.org/wiki/YSR_Congress_Party",
        "name": "Wikipedia - YSR Congress Party",
        "retrieved_at": "2026-04-23T00:00:00+05:30"
      }
    ]
  }
}
