=== prahaladvathsan/sofascore-politics/data/schemas/party.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://political-report-card.example/data/schemas/party.schema.json",
  "title": "Party",
  "type": "object",
  "additionalProperties": false,
  "required": ["id", "name", "short_name", "color", "official_url", "_meta"],
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "short_name": {
      "type": "string"
    },
    "color": {
      "type": "string",
      "pattern": "^#[0-9A-Fa-f]{6}$"
    },
    "official_url": {
      "type": "string",
      "format": "uri"
    },
    "_meta": {
      "$ref": "common.schema.json#/definitions/meta"
    }
  }
}

=== prahaladvathsan/sofascore-politics/data/parties/BRS.json
{
  "id": "BRS",
  "name": "Bharat Rashtra Samithi",
  "short_name": "BRS",
  "color": "#f06292",
  "official_url": "https://brsparty.com/",
  "_meta": {
    "sources": [
      {
        "url": "https://en.wikipedia.org/wiki/Bharat_Rashtra_Samithi",
        "name": "Wikipedia - Bharat Rashtra Samithi",
        "retrieved_at": "2026-04-23T00:00:00+05:30"
      }
    ]
  }
}

=== prahaladvathsan/sofascore-politics/data/parties/DMK.json
{
  "id": "DMK",
  "name": "Dravida Munnetra Kazhagam",
  "short_name": "DMK",
  "color": "#d71920",
  "official_url": "https://www.dmk.in/",
  "_meta": {
    "sources": [
      {
        "url": "https://en.wikipedia.org/wiki/Dravida_Munnetra_Kazhagam",
        "name": "Wikipedia - Dravida Munnetra Kazhagam",
        "retrieved_at": "2026-04-22T00:00:00+05:30"
      }
    ]
  }
}

=== prahaladvathsan/sofascore-politics/data/parties/SHS.json
{
  "id": "SHS",
  "name": "Shiv Sena",
  "short_name": "SHS",
  "color": "#f57c00",
  "official_url": "https://www.shivsena.in/",
  "_meta": {
    "sources": [
      {
        "url": "https://en.wikipedia.org/wiki/Shiv_Sena",
        "name": "Wikipedia - Shiv Sena",
        "retrieved_at": "2026-04-23T00:00:00+05:30"
      }
    ]
  }
}

=== prahaladvathsan/sofascore-politics/data/parties/BJP.json
{
  "id": "BJP",
  "name": "Bharatiya Janata Party",
  "short_name": "BJP",
  "color": "#f58220",
  "official_url": "https://www.bjp.org/",
  "_meta": {
    "sources": [
      {
        "url": "https://en.wikipedia.org/wiki/Bharatiya_Janata_Party",
        "name": "Wikipedia - Bharatiya Janata Party",
        "retrieved_at": "2026-04-22T00:00:00+05:30"
      }
    ]
  }
}

=== prahaladvathsan/sofascore-politics/data/parties/CPM.json
{
  "id": "CPM",
  "name": "Communist Party of India (Marxist)",
  "short_name": "CPI(M)",
  "color": "#d32f2f",
  "official_url": "https://cpim.org/",
  "_meta": {
    "sources": [
      {
        "url": "https://en.wikipedia.org/wiki/Communist_Party_of_India_(Marxist)",
        "name": "Wikipedia - Communist Party of India (Marxist)",
        "retrieved_at": "2026-04-23T00:00:00+05:30"
      }
    ]
  }
}

=== prahaladvathsan/sofascore-politics/data/parties/TDP.json
{
  "id": "TDP",
  "name": "Telugu Desam Party",
  "short_name": "TDP",
  "color": "#fbc02d",
  "official_url": "https://www.telugudesamparty.org/",
  "_meta": {
    "sources": [
      {
        "url": "https://en.wikipedia.org/wiki/Telugu_Desam_Party",
        "name": "Wikipedia - Telugu Desam Party",
        "retrieved_at": "2026-04-23T00:00:00+05:30"
      }
    ]
  }
}

=== prahaladvathsan/sofascore-politics/data/parties/AITC.json
{
  "id": "AITC",
  "name": "All India Trinamool Congress",
  "short_name": "AITC",
  "color": "#22c55e",
  "official_url": "https://aitcofficial.org/",
  "_meta": {
    "sources": [
      {
        "url": "https://aitcofficial.org/",
        "name": "All India Trinamool Congress",
        "retrieved_at": "2026-04-23T00:00:00+05:30"
      }
    ]
  }
}

=== prahaladvathsan/sofascore-politics/data/parties/NTK.json
{
  "id": "NTK",
  "name": "Naam Tamilar Katchi",
  "short_name": "NTK",
  "color": "#dc2626",
  "official_url": "https://www.naamtamilar.org/",
  "_meta": {
    "sources": [
      {
        "url": "https://www.naamtamilar.org/",
        "name": "Naam Tamilar Katchi",
        "retrieved_at": "2026-04-23T00:00:00+05:30"
      }
    ]
  }
}
